services:
  pebble:
    image: ghcr.io/letsencrypt/pebble:latest
    command: -strict -dnsserver 10.30.50.3:8053
    ports:
      - 14000:14000 # HTTPS ACME API
      - 15000:15000 # HTTPS Management API
    networks:
      acmenet:
        ipv4_address: 10.30.50.2
  challtestsrv:
    image: ghcr.io/letsencrypt/pebble-challtestsrv:latest
    command:
    ports:
      - 8055:8055 # HTTP Management API
      - 8053:8053/tcp # DNS TCP
      - 8053:8053/udp # DNS UDP
    networks:
      acmenet:
        ipv4_address: 10.30.50.3
networks:
  acmenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24
