name: Run Pebble
description: Run pabble......

runs:
  using: "composite"
  steps:
    - name: Start Pebble and pebble-challtestsrv
      shell: bash
      run: deno task pebble:start --detach

    - name: Wait for Pebble to be ready
      shell: bash
      run: |
        echo "â³ Waiting for Pebble... ðŸª¨"
        until nc -zv localhost 14000 2>/dev/null; do
          sleep 1
        done
        echo "âœ… Pebble is running!"

    - name: Wait for pebble-challtestsrv to be ready
      shell: bash
      run: |
        echo "â³ Waiting for pebble-challtestsrv... ðŸª¨"
        until nc -zv localhost 8055 2>/dev/null; do
          sleep 1
        done
        echo "âœ… pebble-challtestsrv is running!"

    - name: Run this action
      uses: gacts/run-and-post-run@v1
      with:
        post: |
          deno task pebble:stop
