name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt-lint-check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.
      - run: deno fmt --check
      - run: deno lint
      - run: deno check --doc .
      - run: deno task test:unit
      - run: deno task build:npm:unit
